# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.15.11
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=2.3.1-1.20.1
maven_group=net.s3lmoni.guaxiorigin
archives_base_name=guaxi-origin

# Dependencies
fabric_api_version=0.92.7+1.20.1
## Origins
origins_version=1.10.2+mc.1.20.x
apoli_version=2.9.0+mc.1.20.x
calio_version=1.11.0+mc.1.20.x
## Pehkui
pehkui_version=3.8.3